name: Build & Test

on: [ push, pull_request, workflow_call, workflow_dispatch ]

jobs:
  check_linux:
    name: Performing Linux Build / Update
    runs-on: ubuntu-22.04
    steps:
      - name: "Install Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get pkg-config libpipewire
        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Preparing Cache..
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-

      - name: Running Tests
        run: cargo check --all-features

      - name: Checking Formatting
        run: cargo fmt --all -- --check

      - name: Performing Clippy Test
        run: cargo clippy --all-targets --all-features -- -D warnings